### ISSUE TITLE
 yurt-dashboard:0.0.6 image do not exist

### ISSUE THREAD

**Issue by yjqg6666** [openyurtio/yurt-dashboard#46]
[yurt-dashboard@hub.docker.com](https://hub.docker.com/r/openyurt/yurt-dashboard/tags) only have latest tag.
Please provide versioned tag.

Related to openyurtio/openyurt-helm#15 .

**Comment by rambohe-ch** [comment]
@luc99hen PTAL

**Comment by luc99hen** [comment]
Thank you for your suggestions. Dashboard project is currently being upgraded and the image has not been ready yet. We 'll let you know when it's ready.

**Comment by yjqg6666** [comment]
So pls. update the helm image value, the tag should be latest. @luc99hen

**Comment by luc99hen** [comment]
> So pls. update the helm image value, the tag should be latest. @luc99hen
Sorry for not making it clear, but the dashboard image on docerhub cannot be used normally for the time being.
